Mobile menu javascript
principles31/portfolio pull request #11
Opened 2022-04-12 10:45 UTC by principles31

2022-04-13 14:47 UTC, ShadyShawkat requested changes
## Hi Team, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-13 14:47 UTC, ShadyShawkat commented on index.html
> +        </ul>
- [ ] Kindly make sure that the modal takes the entirety of the screen's width and height and the user can't scroll to the page's content when the modal is opened.
![image](https://user-images.githubusercontent.com/62290545/163202846-4354e7f2-f135-4109-8f2e-84b3d0f2b1cf.png)

2022-04-13 14:47 UTC, ShadyShawkat commented on index.html
> +        </ul>
- [ ] Please make sure that the mobile hamburger menu button only appears on the mobile view and not the desktop view. Currently, the hamburger menu is displayed on both the mobile and desktop views.
![image](https://user-images.githubusercontent.com/62290545/163203451-310969a4-0179-46e3-a587-804a06d7b686.png)

2022-04-13 14:47 UTC, ShadyShawkat commented on index.html
> +          <li class=""><a href="#contact">Contact</a></li>
- [ ] Please be sure that the modal is closed and hidden after the user clicks any nav link or the `x` button. Currently, the modal isn't closed or hidden after the user clicks any nav link.
- [ ] Kindly make sure that after the modal is closed through nav links or the `x` button, the page returns to the original design, and only the modal is hidden out of sight. Currently, after the modal is closed, the following behavior occurs. (See image below)

Before opening the modal:
![image](https://user-images.githubusercontent.com/62290545/163207081-b34989c2-9fb4-47a5-89c4-f7e32cb7ec8b.png)
After closing the modal:
![image](https://user-images.githubusercontent.com/62290545/163207292-5d273796-fe98-48fe-9e57-5ba2ff8de4b4.png)

2022-04-14 21:04 UTC, CollinsTatang requested changes
Hi Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️

- [x] The hamburger menu is not stable and I can't find the closing `X` bottom.
### **Take a look at the mobile view**

https://user-images.githubusercontent.com/55596970/163474599-e26d101e-dea8-4199-86bd-1c6016bf340c.mp4




_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-14 22:02 UTC, principles31 commented
@CollinsTatang, thank you for the feedback. 
function showmodal() {
  modal.style.display = 'block';
  flexUl.style.display = 'block';
}

btn.addEventListener('click', showmodal);

function hideModal() {
  modal.style.display = 'none';
  flexUl.style.display = 'none';
}

flexUl.addEventListener('click', hideModal);
span.addEventListener('click', hideModal);

please kindly help which function best for implementing the above issues hence ....function.addEventListener is rejected by the javascript ESlint.

2022-04-15 04:03 UTC, CollinsTatang commented
> @CollinsTatang, thank you for the feedback. function showmodal() { modal.style.display = 'block'; flexUl.style.display = 'block'; }
> 
> btn.addEventListener('click', showmodal);
> 
> function hideModal() { modal.style.display = 'none'; flexUl.style.display = 'none'; }
> 
> flexUl.addEventListener('click', hideModal); span.addEventListener('click', hideModal);
> 
> please kindly help which function best for implementing the above issues hence ....function.addEventListener is rejected by the javascript ESlint.

Hello @principles31 
Can we have a call?

2022-04-15 08:36 UTC, principles31 commented
@CollinsTatang Yes  please, I'm available

2022-04-15 09:35 UTC, CollinsTatang commented
> 

OK

2022-04-15 10:19 UTC, principles31 commented
@CollinsTatang It has been resolved now. Thank you for your effort to improve my code. the best reviewer so far ...keep it up

2022-04-15 10:32 UTC, CollinsTatang commented
Thanks 
All the best as you move to the next project

2022-04-15 10:33 UTC, CollinsTatang commented
> @CollinsTatang It has been resolved now. Thank you for your effort to improve my code. the best reviewer so far ...keep it up

Thanks
All the best as you move to the next project

2022-04-15 15:58 UTC, AnselemOdims approved these changes
### Hi  @principles31 🙋‍♀️, 
Good job in making the required changes 👏 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Use the tag @AnselemOdims for a quicker reply


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-15 16:06 UTC, principles31 commented
@AnselemOdims @CollinsTatang @ShadyShawkat.Thank you for your approval. it takes a lot to make this project work and you are part of that success and the previous reviewers.

2022-04-15 16:06 UTC, merged